trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dqsourceanalyzer'
  tag: 'latest'

steps:
  - checkout: self

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: '4031b34e-6354-4257-94de-a85346a777ae/PurviewDataGov'

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      arguments: 
        --build-arg PIP_INDEX_URL=$(PIP_INDEX_URL)
      Dockerfile: pdgdqsourceanalyzer/Dockerfile
      tags: |
        $(tag)

  - task: Docker@2
    displayName: 'Push the image to ACR'
    inputs:
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      command: push
      tags: |
        $(tag)
