trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dqsourceanalyzer'
  tag: 'latest'
  PIP_EXTRA_INDEX_URL: 'https://msdata.pkgs.visualstudio.com/4031b34e-6354-4257-94de-a85346a777ae/_packaging/PurviewDataGov/pypi/simple/'

steps:
  - checkout: self

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'PurviewDataGov'

  - bash: |
      pip3 install pyodbc==5.1.0 --extra-index-url https://msdata.pkgs.visualstudio.com/4031b34e-6354-4257-94de-a85346a777ae/_packaging/PurviewDataGov/pypi/simple/
      echo "##vso[task.setvariable variable=artifactoryUrl;]$PIP_EXTRA_INDEX_URL"
      echo "Artifactory URL is: $PIP_EXTRA_INDEX_URL"
    displayName: Export Artifactory URL

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: build
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      arguments: --build-arg PIP_EXTRA_URL=$(artifactoryUrl)
      Dockerfile: pdgdqsourceanalyzer/Dockerfile
      tags: |
        $(tag)

  - task: Docker@2
    displayName: 'Push the image to ACR'
    inputs:
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      command: push
      tags: |
        $(tag)
