trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dqsourceanalyzer'
  tag: 'latest'

steps:
  - checkout: self

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'PurviewDataGov'

  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      command: build
      Dockerfile: pdgdqsourceanalyzer/Dockerfile
      tags: |
        $(tag)

  - task: Docker@2
    displayName: Push the image to ACR
    inputs:
      containerRegistry: 'dq-source-analyzer-testing'
      repository: $(imageName)
      command: push
      tags: |
        $(tag)