#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - develop

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false
- name: enableSdlTools
  displayName: 'Enable SDL tools' # Add option to enable SDL tools on an ad-hoc basis. Some SDL tools aren't required for unofficial builds.
  type: boolean
  default: false
  
variables:
  system.debug: ${{ parameters.debug }}
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: http://onebranch.azurecr.io/linux/ubuntu-1804:latest # for Linux jobs https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/4582/
  OneBranchTemplate: 'v2/OneBranch.NonOfficial.CrossPlat.yml@templates'

extends:
  template: Pipeline.ParameterizedStages.yml
  parameters:
    OneBranchTemplate: ${{ variables.OneBranchTemplate }}
    enableSdlTools: ${{parameters.enableSdlTools}}