#################################################################################
#                         OneBranch Pipelines - Official                        #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - develop

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  system.debug: ${{ parameters.debug }}
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:24.04 # for Linux jobs https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/4582/
  OneBranchTemplate: 'v2/OneBranch.Official.CrossPlat.yml@templates'
  Codeql.PublishDatabaseLog: true
  Codeql.Cadence: 0

extends:
  template: Pipeline.ParameterizedStages.yml
  parameters:
    OneBranchTemplate: ${{ variables.OneBranchTemplate }}
    enableSdlTools: true