#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

name: $(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - develop

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false
- name: enableSdlTools
  displayName: 'Enable SDL tools' # Add option to enable SDL tools on an ad-hoc basis. Some SDL tools aren't required for unofficial builds.
  type: boolean
  default: false
  
variables:
  system.debug: ${{ parameters.debug }}
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: mcr.microsoft.com/onebranch/cbl-mariner/build:2.0 # for Linux jobs https://onebranch.visualstudio.com/OneBranch/_wiki/wikis/OneBranch.wiki/4582/
  OneBranchTemplate: 'v2/OneBranch.NonOfficial.CrossPlat.yml@templates'

extends:
  template: Pipeline.ParameterizedStages.yml
  parameters:
    OneBranchTemplate: ${{ variables.OneBranchTemplate }}
    enableSdlTools: ${{parameters.enableSdlTools}}
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Use Python 3.x'

- script: |
    python -m pip install --upgrade pip setuptools --trusted-host pypi.org --trusted-host files.pythonhosted.org
  displayName: 'Upgrade pip and setuptools with trusted hosts'

- script: |
    pip install <your-packages-here> --trusted-host pypi.org --trusted-host files.pythonhosted.org
  displayName: 'Install packages with trusted hosts'