#################################################################################
#                         OneBranch Pipelines - Official                        #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

stages:
  - stage: docker
    dependsOn: linux_build_stage
    jobs:
    - job: linuxContainers # build linux images
      pool:
        type: docker
        os: linux
      steps:
        - task: DownloadPipelineArtifact@2
          displayName: '📥 Download and Explode artifacts from previous stage'
          inputs:
            artifactName: 'drop_linux_build_stage_linux_job'
            targetPath: '$(Build.SourcesDirectory)/dst'
            artifact: drop_linux_build_stage_linux_job
        - task: PipAuthenticate@1
          displayName: 'Pip Authenticate'
          inputs:
            artifactFeeds: '4031b34e-6354-4257-94de-a85346a777ae/PurviewDataGov'
        - task: onebranch.pipeline.imagebuildinfo@1
          displayName: '🏗 Build DataQualityService Docker Image'
          inputs:
            repositoryName: dataqualityservice
            dockerFileRelPath: PdgDqsourceAnalyzerDockerFiles/Dockerfile
            dockerFileContextPath: PdgDqsourceAnalyzerDockerFiles
            registry: dataqualityacr.azurecr.io
            arguments: --build-arg PIP_INDEX_URL=$(PIP_INDEX_URL)
            addPipelineData: false
            push: false
            saveImageToPath: PdgDqsourceAnalyzerImage.tar.gz
            buildkit: 1
            enable_network: true # Disable it once dotnet performance tools are available in nuget feed
            build_tag: $(Build.BuildNumber) # Docker image tag
            compress: true
            