apiVersion: v1
kind: Service
metadata:
  name: dataquality-service
  annotations:
    service.beta.kubernetes.io/azure-allowed-service-tags: {{ required "Parameter dqs.allowedServiceTags must be set" .Values.dqs.allowedServiceTags }}
spec:
  selector:
    app: purview-dqs
  ports:
    - protocol: TCP
      port: 443