apiVersion: v1
kind: Secret
metadata:
  name: mdsd-auth
type: Opaque
data:
  gcscert.pem: {{ .Values.gcscert.pem | b64enc }}
  gcskey.pem: {{ .Values.gcskey.pem | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mdm-auth
type: Opaque
data:
  mdm-cert.pem: {{ .Values.gcscert.pem | b64enc }}
  mdm-key.pem: {{ .Values.gcskey.pem | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azsecpack-auth
type: Opaque
data:
  azsecpack-cert.pem: {{ .Values.gcscert.pem | b64enc }}
  azsecpack-key.pem: {{ .Values.gcskey.pem | b64enc }}