apiVersion: v1
kind: Service
metadata:
  name: geneva-services
  labels:
    app: geneva-services
spec:
  type: ClusterIP
  ports:
    - name: mdm-statsd-udp
      protocol: UDP
      port: 8125
      targetPort: 8125
  selector:
    name: geneva-services