apiVersion: v1
kind: Service
metadata:
  name: purview-dqsa-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ required "Parameter dqs.publicIpGroup must be set to the resource group name where the public IP is defined" .Values.dqs.publicIpGroup }}
    service.beta.kubernetes.io/azure-allowed-service-tags: {{ required "Parameter dqs.allowedServiceTags must be defined" .Values.dqs.allowedServiceTags }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ required "Parameter dqs.publicIp must be set to a valid public IP" .Values.dqs.publicIp }}
  externalTrafficPolicy: Local
  ports:
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: purview-dqsa