# mdsd certificate store
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mdsd-secret
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ .Values.gcs_keyvault_name | quote }}
    cloudName: {{ .Values.gcs_cloud_name | quote }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.gcs_cert_name | quote }}
          objectType: secret
          objectAlias: "cert.pem"
          objectVersion: ""
    tenantId: {{ .Values.gcs_keyvault_tenant | quote }}
---
# mdm and azsecpack store
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mdm-azsecpack-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ .Values.gcs_keyvault_name | quote }}
    cloudName: {{ .Values.gcs_cloud_name | quote }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.gcs_cert_name | quote }}
          objectType: cert
          objectAlias: gcscert.pem
        - |
          objectName: {{ .Values.gcs_cert_name | quote }}
          objectType: secret
          objectAlias: gcskey.pem
    tenantId: {{ .Values.gcs_keyvault_tenant | quote }}