apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watsonagent
  namespace: kube-system
  labels:
    app: watsonagent
spec:
  selector:
    matchLabels:
      name: watsonagent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: watsonagent
    spec:
      hostNetwork: true
      enableServiceLinks: false
      containers:
        #Watson
        - name: watsonagent
          image: mcr.microsoft.com/azure-watson/agent/agent_mariner:1.21.13.0
          securityContext:
            privileged: true
          env:
          - name: INCOMING_QUEUE
            value: /azure-watson/cores
          - name: REPORT_QUEUE
            value: /azure-watson/queue
          - name: MDSD_ROLE_PREFIX
            value: /var/run/mdsd
          - name: OS_RELEASE_INFO_DIR
            value: /OSR
          - name: OS_SUBRELEASE_INFO_DIR
            value: /OSSubrelease
          - name: WA_CORE_PATTERN
            value: /azure-watson/cores/%e-%p-%h-%t
          resources:
            requests:
              cpu : "50m"
              memory: "64Mi"
            limits:
              cpu : "1000m"
              memory: "3072Mi"
          volumeMounts:
            - mountPath: /azure-watson # Contains both the incoming queue and report queue directories
              name: crashdump-mount
            - mountPath: /var/run/mdsd
              name: mdsd-run-vol
            - mountPath: /OSR
              name: container-os-release
            - mountPath: /OSSubrelease
              name: container-os-subrelease
      volumes:
        - name: crashdump-mount
          hostPath:
            path: /home/docker/azure-watson
        - name: mdsd-run-vol
          hostPath:
            path: /var/run/mdsd-containers
        - name: container-os-release
          hostPath:
            path: /home/docker/OsRelease
        - name: container-os-subrelease
          hostPath:
            path: /home/docker/OsSubrelease